### PR TITLE
WIP: Add coil distance plot

### PR DESCRIPTION
**Pull request by larsoner**
`fig = mnefun.plot_good_coils(raw)` does this:

screenshot from 2017-05-03 16-25-52

### CODE REVIEW

**Comment by kambysese** [comment]
This is pretty sweet. I am still not clear on how "goodness" is determined. This presumably could guide cHPI weighting during averagine?

**Comment by Eric89GXL** [comment]
Same criteria as MF, namely inter-coil distances less than some threshold (by default 5mm).

**Comment by kambysese** [comment]
This takes a pretty long time to generate fig. is that expected?

image
Does this give any sort of indication whether the dataset might be a good case for cHPI weighting?

**Comment by Eric89GXL** [comment]
> This takes a pretty long time to generate fig. is that expected?

That's a bit too vague to say yes/no (are we talking minutes or hours?). I'd expect on the order of minutes for long recordings because it needs to compute coil positions. To make it faster you can set the `t_step` to be longer.

**Comment by kambysese** [comment]
Minutes.

**Comment by larsoner** [comment]
@kambysese is the API okay for you? If so I'll probably merge.

Also, from talking to @staulu it might be nice to:

1. build some of this into a QA report for each subject. We could probably build this plot in to the `report` functionality we already have.
2. If n_coils < 3 at any point, emit a warning that X% of time (Y sec) was unlocalizable for run Z

WDYT? Anything else you would expect to be useful from this?

**Comment by kambysese** [comment]
```
raw = io.read_raw_fif('subj_01_funloc_raw.fif', allow_maxshield='yes')
fig = mnefun.plot_good_coils(raw)
```

Returns

> Traceback (most recent call last):
>   File "/home/ktavabi/miniconda3/envs/py2.7/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-6-cbfb86f14166>", line 1, in <module>
>     fig = mnefun.plot_good_coils(raw)
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 2698, in plot_good_coils
>     t, counts, n_coils = compute_good_coils(raw, t_step, t_window, dist_limit)
> TypeError: 'NoneType' object is not iterable
>     t=0.000:     0 < 3 HPI coils turned on, skipping fit

```
raw = io.read_raw_fif('subj_02_funloc_raw.fif', allow_maxshield='yes')
fig = mnefun.plot_good_coils(raw)
```
Produces this...
image

Does that make sense? 
`plot_good_coils` LGTM `compute_good_coils` I need to think through to understand before I can comment.

**Comment by larsoner** [comment]
Nice catch on `subj_01_funloc_raw`, it's fixed now. I'll merge this and we can iterate further if we find other problems, thanks for the look @kambysese

**Pull request merged**
