### PR TITLE
FIX: Move simulation code

### LINKED ISSUE #98: head pos sanity check error
Hi @Eric89GXL,
 I'm encountering the following error (for one subj) when pushing raw files and sss script to workstation with @kambysese's data.
* Head positions from quaternion file for this subj look relatively stable. 

AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05

(mismatch 100.0%)
 x: array([[-0.971479,  0.236196, -0.02098 ],
       [ 0.193013,  0.736257, -0.648592],
       [-0.137748, -0.634143, -0.760847]])
 y: array([[-0.971414,  0.236547, -0.020009],
       [ 0.192648,  0.736266, -0.648691],
       [-0.138714, -0.634002, -0.760789]])

### PR DESCRIPTION
**Pull request by Eric89GXL**
Refactors simulation code now that it's in mne-python.

Closes #98.

### CODE REVIEW

**Comment by wronk** [comment]
I was thinking of focusing on SSS for the last couple weeks until GSoC ends. What do you think?

The PR should be getting close though. I'm currently stuck on some error that I'm having trouble reproducing consistently on my local machine. After that is fixed, I think the remaining work is porting over the improvements you made to this analogous function in mnefun.

**Comment by Eric89GXL** [comment]
I think you should indeed work on the SSS code full time for the next few weeks, or longer if KC lets you :) I might try to fix the bugs with the simulation code, if that's okay. It's not great to leave the PR open too long, plus I am coming back to this code more now and changes (like this) will need to be made in two places right now.

**Comment by wronk** [comment]
No problem, have at it :)

**Comment by Eric89GXL** [comment]
@rkmaddox do you have time to take a look at this in the next day or two?

**Comment by rkmaddox** [comment]
It all looks reasonable to me. +1 for merge.

**Comment by Eric89GXL** [comment]
Thanks Ross

**Pull request merged**
