### PR TITLE
Demo notebook

### PR DESCRIPTION
**Pull request by kambysese**
@Eric89GXL for some reason I had to remove `funloc` as ignored directory in `.gitignore` and redo the whole PR

### CODE REVIEW

**Comment by Eric89GXL** [comment]
You don't actually need to do it that way. git add - f would also work.

**Comment by kambysese** [comment]
So wrt to #162 leave `.gitignore` as is in master and use git add -f ...funloc/notebook?

**Comment by Eric89GXL** [comment]
That one is okay for now, but next time prefer git add -f to modifying
gitignore

**Comment by Eric89GXL** [comment]
LGTM, thanks

**Pull request merged**
