### PR TITLE
ENH: Add support for regex reject by annot

### PR DESCRIPTION
**Pull request by larsoner**
Completely untested, feel free to test @drammock ! In theory you should get a nice `print` statement when you pass a `str`.

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock do you want to try running the unified PreK pipeline on this branch before I merge? I'm tempted to merge as-is and fix whatever we need in a follow-up PR. I put in a bunch of fixes needed to work with Kam's data.

**Comment by drammock** [comment]
go ahead and merge, I'm busy with other aspects of PREK right now, may be a while before we're ready to run the unified pipeline.

**Comment by ktavabi** [comment]
This merged appears to have failed b/c of Travis. @larsoner I am now running your `reject` branch on badbaby data.

**Comment by larsoner** [comment]
I think the code churn / increased difficulty of proper `git blame` from black is probably not worth the benefits it brings in terms of uniformity. Maybe we should do it in a separate PR for the whole repo at some point but I'd rather lag than lead MNE in adopting that convention

**Comment by ktavabi** [comment]
> Maybe we should do it in a separate PR for the whole repo at some point but I'd rather lag than lead MNE in adopting that convention

SGTM But I am not sure why my local modifications got merged into your branch?! 😬

**Comment by larsoner** [comment]
> SGTM But I am not sure why my local modifications got merged into your branch?! 

Must have been a `git push` done by some software you are using (codestream?)

**Pull request merged**
