### PR TITLE
ENH: Add reconstruction

### PR DESCRIPTION
**Pull request by Eric89GXL**
cc @staulu @mdclarke on this branch you should be able to this:
```
import os.path as op

import mne
from mnefun import plot_reconstruction

data_path = mne.datasets.sample.data_path()
raw = mne.io.read_raw_fif(op.join(data_path, 'MEG', 'sample',
                          'sample_audvis_raw.fif'), preload=True)
raw.pick_types(meg=True, eeg=False, eog=True, stim=True, exclude=())
events = mne.find_events(raw, 'STI 014')
raw.add_proj(mne.preprocessing.compute_proj_eog(raw)[0])
raw.add_proj(mne.preprocessing.compute_proj_ecg(raw)[0])
epochs = mne.Epochs(raw, events, {'Left auditory': 1}, -0.2, 0.5,
                    baseline=(None, 0), proj='delayed',
                    reject=dict(grad=4000e-13, mag=4e-12, eog=150e-6))
evoked = epochs.average()

plot_reconstruction(evoked)
```
And obtain this:
figure_1

@mdclarke let me know if it works for you. I expect that we'll need to tweak e.g. the y-axis limits.

### CODE REVIEW

**Comment by mdclarke** [comment]
@Eric89GXL 
I can't import plot_reconstruction

I'm on your 'Eric89GXL/info-sss' branch of mnefun, is this right?

**Comment by Eric89GXL** [comment]
No, check out the top of the page the branch name is listed up there (recon)

**Comment by mdclarke** [comment]
@Eric89GXL 

gotcha. Thanks

**Comment by mdclarke** [comment]
@Eric89GXL 
script works for me

**Comment by Eric89GXL** [comment]
Thanks, I'll go ahead and merge for now then

**Pull request merged**
