### PR TITLE
MRG, ENH: Add Python automatic bad channel path

### PR DESCRIPTION
**Pull request by larsoner**
Add `find_bad_channels_maxwell` to `mnefun` alongside some Report fixes.

### CODE REVIEW

**Comment by larsoner** [comment]
@NeuroLaunch can you take a look at this PR, too? The updated `overview` page (with the full Python-based workflow and some fixes) has been [rendered here](https://124-17719360-gh.circle-artifacts.com/0/html/overview.html).

**Comment by larsoner** [comment]
@drammock feel free to look too

**Comment by larsoner** [comment]
I'll go ahead and merge to get these fixes in, but @NeuroLaunch still feel free to review and I can open another PR with fixes

**Comment by drammock** [comment]
By the way I did read through the new docs page, but got distracted before I had a chance to leave a (glowing positive) review. It looks great!

**Comment by NeuroLaunch** [comment]
The doc page looks fine, though I'm not certain of the role of the output file "_raw_maxbad.txt".  I'll check it out when I test the code with the /funloc example.

**Pull request merged**
