### PR TITLE
Plot drop logs

### PR DESCRIPTION
**Pull request by kambysese**
@Eric89GXL setting `Params` attribute `plot_drop_logs` to False by default to kill onslaught of figure windows.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
@kambysese your commit history is bad.

Maybe we should merge #168 first. I'll set it to MRG

**Comment by kambysese** [comment]
> your commit history is bad

"Bad" is kinda harsh, it's only two extraneous commits long! :smile: and that only after a successful conflict resolution. I take it you're in the strictly linear commit history camp?

**Comment by Eric89GXL** [comment]
>  I take it you're in the strictly linear commit history camp?

Ideally, yeah. But practically, looking at this `diff` it contains stuff from #168 so it's hard to know what you are trying to change.

**Comment by kambysese** [comment]
Ok so you will be merging #168 and I need to merge or rebase my PR branch? I never know how best to clean up the commit history.

**Comment by Eric89GXL** [comment]
You should make your new branches off of `upstream/master` and it will avoid these issues. When you created this branch, you must have done so while on my branch, which is not merged yet (and the commit history could change before merge).

**Comment by Eric89GXL** [comment]
...in the meantime, you'll probably need to start a new branch based on `upstream/master` and `cherry-pick` your commit. `git rebase` won't do anything because there are three new commits in this branch not in `upstream/master`, two of mine and one of yours.

**Comment by kambysese** [comment]
> You should make your new branches off of upstream/master and it will avoid these issues. When you created this branch, you must have done so while on my branch, which is not merged yet (and the commit history could change before merge).

I typically do that. Are you sure you weren't working in upstream/master because `177d80` is showing as `WIP:Updates for latest MNE` in upstream/master log.

**Comment by Eric89GXL** [comment]
> Are you sure you weren't working in upstream/master because 177d80 is showing as WIP:Updates for latest MNE in upstream/master log

I don't see that:

https://github.com/LABSN/mnefun/commits/master

**Comment by kambysese** [comment]
Apologies I stand corrected

**Pull request closed without merging**
