### PR TITLE
FIX:additional plot window process blocking behavior.

### PR DESCRIPTION
**Pull request by kambysese**
@Eric89GXL blocking behavior for psd plots. 
@jyeatman can you try this out to see if it works?

### CODE REVIEW

**Comment by Eric89GXL** [comment]
I expect this to work, @jyeatman let us know

**Comment by jyeatman** [comment]
I pulled that branch and now the code crashes with the following error:

Traceback (most recent call last):
  File "/home/jyeatman/git/ilabs/nlr/nlr_analysis.py", line 246, in <module>
    print_status=False
  File "/home/jyeatman/git/mnefun/mnefun/_mnefun.py", line 453, in
do_processing
    outs[ii] = func(p, subjects, run_indices)
  File "/home/jyeatman/git/mnefun/mnefun/_mnefun.py", line 1882, in
plot_raw_psd
    picks=None, block=False)
TypeError: plot_psd() got an unexpected keyword argument 'block'

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by Eric89GXL** [comment]
You might also need to update your version of `mne-python` to latest `master`.

**Comment by jyeatman** [comment]
I'm up to date on mne and mnefun

Jason D. Yeatman, PhD
Assistant Professor, Institute for Learning & Brain Sciences (I-LABS)
Department of Speech & Hearing Sciences
University of Washington
http://depts.washington.edu/bdelab/

**Comment by Eric89GXL** [comment]
@kambysese did you test this fix? I don't think there's a `block` param in `plot_psd`:

https://github.com/mne-tools/mne-python/blob/master/mne/io/base.py#L1379

You might be able to do `show=False` instead...?

**Comment by kambysese** [comment]
@Eric89GXL PEBCAK.  I botched this one up.  Things are OK on my end,  which means I tested on another branch. There is no block argument for plot_psd.  The show=False should be the solution.  Sorry @jyeatman. I can try to correct this later tonight if I find Internet access with my laptop.

**Comment by kambysese** [comment]
@Eric89GXL tested locally with mnefun example data; should address @jyeatman your issue, LMK.

**Comment by Eric89GXL** [comment]
This should work, merging. @jyeatman let us know if current `master` doesn't fix the problem now.

**Pull request merged**
