### PR TITLE
fix indexing bug

### PR DESCRIPTION
**Pull request by jjnurminen**
This fixes a "double indexing" bug, where MEG channels were already picked into a 306-dim matrix and then again indexed with `pick_grad` and `pick_mag`. It manifested as an IndexError in a case where the fiff channel list did not start with MEG channels.

### CODE REVIEW

**Comment by jjnurminen** [comment]
(also changed some `.transpose()` calls to `.T`, not related to the bug)

**Comment by Eric89GXL** [comment]
LGTM, ready to go from your end?

**Comment by jjnurminen** [comment]
I'm ready

**Comment by Eric89GXL** [comment]
Thanks for the fix

**Pull request merged**
