### PR TITLE
Notebook demo

### PR DESCRIPTION
**Pull request by kambysese**
@Eric89GXL The WIP notebook version of `analysis.py` seemed to have gone over well with everyone in attendance. I wonder if it makes sense to include in the funloc directory. LMKWYT.

### CODE REVIEW

**Comment by Eric89GXL** [comment]
Your PR doesn't change any files. You added a file and removed it

**Comment by kambysese** [comment]
This is weird! The file was moved from `.../examples` to `/examples/funloc`. At least that is the case locally :/

**Comment by Eric89GXL** [comment]
Did you do mv or git mv

**Comment by kambysese** [comment]
Ugh IDK apparently Pycharm isn't as smart about moving IPYNB files around.

**Pull request closed without merging**
