### PR TITLE
Fix: use reject by annot regex during cov step

### PR DESCRIPTION
**Pull request by drammock**
allows regex-based `reject_epochs_by_annot` when epoching during covariance computation

### CODE REVIEW

**Comment by drammock** [comment]
confused by the CircleCI fail:
```
/home/circleci/project/mnefun/_utils.py:docstring of mnefun._utils.make_dipole_projectors:23: WARNING: undefined label: tut_logging
```
but `git grep tut_logging` returns no results in the repo.  Looking at the docstring, `tut_logging` doesn't show up, unless it's part of the `%(verbose)s` expansion?

**Comment by larsoner** [comment]
It's part of verbose, I had this problem in mne-connectivity, too. The fix was maybe to set `default_role = 'py:obj'` there in `conf.py` (?). Can't remember

**Comment by drammock** [comment]
ok, I'm stumped. In both mnefun and mne-connectivity, `grep -r tut_logging .` returns nothing.  In MNE-Python (where `verbose` is imported from, all I get is this:

```console
$ grep -r tut_logging .
Binary file ./mne/decoding/__pycache__/receptive_field.cpython-39.pyc matches
Binary file ./mne/utils/__pycache__/docs.cpython-39.pyc matches
Binary file ./mne/inverse_sparse/__pycache__/mxne_optim.cpython-39.pyc matches
```
I already tried `py:obj`, and combed through several other commits in the mne-connectivity history looking for mention of verbose or tut_logging, and couldn't find anything.  @adam2392 do you remember hitting this issue recently?  If so can you point me at a solution?

**Comment by larsoner** [comment]
I think it's tut-logging in MNE (and sphinx might convert hyphens to underscores or vice versa somewhere)

**Comment by larsoner** [comment]
Or maybe we need to use the dev version of MNE for circle if we don't already

**Comment by larsoner** [comment]
```
mne/utils/docs.py:    and :ref:`Logging documentation <tut-logging>` for more).
```
Upstream we should maybe call this `python:tut-logging` or so

**Comment by drammock** [comment]
yep, as long as you're OK with not fixing the tut-logging problem here.

**Comment by drammock** [comment]
> (and sphinx might convert hyphens to underscores or vice versa somewhere)

this may actually result from @alexrockhill's recent overhaul to make all our link target names consistent.

**Comment by larsoner** [comment]
Now the two remaining warnings are legitimate:
```
/home/circleci/project/doc/overview.rst:141: WARNING: py:obj reference target not found: SUBJ/raw_fif/SUBJ_prebad.txt`
/home/circleci/project/doc/overview.rst:722: WARNING: py:obj reference target not found: /.mnefun/mnefun.json
```

**Comment by drammock** [comment]
going to merge this since @larsoner approved it, CIs are all green, and I need it

**Pull request merged**
