### PR TITLE
FIX: Fix proj

### LINKED ISSUE #179: PCA procedure
@larsoner I noticed that even when all `params.proj_nums` are set to `[0, 0, 0]` it looks like `do_preprocessing_combined` still computes PCA. Is that normal/expected behavior?

### PR DESCRIPTION
**Pull request by larsoner**
Closes #179.

@kambysese can you see if this fixes your problem?

### CODE REVIEW

**Comment by kambysese** [comment]
Nope. Threw...

> Traceback (most recent call last):
>   File "/home/ktavabi/Projects/ibis/ibis/preprocess.py", line 115, in <module>
>     print_status=True
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 614, in do_processing
>     outs[ii] = func(p, subjects, run_indices)
>   File "/home/ktavabi/Projects/mnefun/mnefun/_mnefun.py", line 1925, in do_preprocessing_combined
>     if projs.shape != (3, 3):
> AttributeError: 'list' object has no attribute 'shape'

`projs` is a list at ln 1925 and even if the number of desired components is [0, 0, 0] for the different projection types projs[0].shape is always 3-by-3. Or am I missing something?

**Comment by larsoner** [comment]
Should be fixed now.

You shouldn't pass `[0, 0, 0]` but `[[0] * 3] * 3]` or any equivalent. If you want a shortcut, we'll need to add it.

**Comment by kambysese** [comment]
Okay, working now. Not sure how bc I've been passing [[0, 0, 0], [0, 0, 0], [0, 0, 0]], not just [0, 0, 0] and that list is shape 3x3.

**Comment by larsoner** [comment]
Your report from #179 was that you used `[0, 0, 0]`, which is the wrong shape

**Comment by larsoner** [comment]
(`[[0, 0, 0], [0, 0, 0], [0, 0, 0]]` should already work in `master`)

**Comment by kambysese** [comment]
I stand corrected. Head taking penalty shots at my arse. Sorry to waste your time.

**Comment by larsoner** [comment]
It's alright, we'll at least get a more reasonable error now

**Pull request merged**
