### PR TITLE
ENH: Add counts and channel name

### LINKED ISSUE #296: ENH: Add number of epochs for SSP/ECG to report

### PR DESCRIPTION
**Pull request by larsoner**
@nordme this is what the `funloc` data look like with this PR:

Screenshot from 2020-07-07 17-34-19

WDYT? Solid lines are all projected traces at the same scale. Dashed are each normalized individually. So for the EOG you can see that the first component is much larger than the other two.

Closes #296

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock feel free to comment as well

**Comment by larsoner** [comment]
(and @NeuroLaunch if you're interested you can comment, too)

**Comment by nordme** [comment]
Cool. For the 'N=26/28' part, is the 26 the used epochs and the 28 the total number of events detected?

**Comment by larsoner** [comment]
Yes indeed. Maybe I should add a beat and blink per minute, too...

**Comment by nordme** [comment]
Sounds good. Also, yes, bpm would be lovely.

**Comment by larsoner** [comment]
Screenshot from 2020-07-07 19-53-44

**Comment by drammock** [comment]
LGTM!

**Pull request merged**
