### PR TITLE
ENH: Add drop_log plotting

### PR DESCRIPTION
**Pull request by larsoner**
Adds `drop_log` plotting and fixes a problem with `fit_data` being `None` in report.

### CODE REVIEW

**Comment by larsoner** [comment]
@ktavabi feel free to review when you get a chance

**Comment by ktavabi** [comment]
LGTM. Do you want to also add the option to the example script?

**Comment by larsoner** [comment]
It's enabled by default so shouldn't need to do anything to get it to show up. I guess it could be added to expose the option, is that what you had in mind?

**Comment by ktavabi** [comment]
Yeah, that is what I was referring to.

**Comment by larsoner** [comment]
> Also, would this be considered DRY?

One is for during-processing and the other is for the report. I think they serve different enough purposes to keep them separate.

**Pull request merged**
